### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by psi-skillian** [chrisstoll1/Square9APIHelperLibrary#5]
Hi, @chrisstoll1, thanks for making this project, I'm very interested in trying it out, but I am unable to find its license so that I can know what I am allowed to do or not.  Can you add a license such as one from [choosealicense.com](https://choosealicense.com/)?

**Comment by chrisstoll1** [comment]
@psi-skillian Uploaded a license! Thanks for the interest 

https://github.com/chrisstoll1/Square9APIHelperLibrary/blob/master/LICENSE
